### ISSUE TITLE
Settings not persisted at all

### ISSUE THREAD

**Issue by stirante** [Unthrottled/AMII#57]
Today after updating to 1.5.1, all settings were lost and it seems I can't change them now.
https://s3.eu-central-1.amazonaws.com/files.stirante.com/2021-01-26_22-33-10.mp4

I noticed it after the sound, I previously disabled, startled me.
![image](https://amii-assets.s3.amazonaws.com/visuals/crying/aqua_crying_one.gif)

**Comment by Unthrottled** [comment]
Whoops! It looks like I missed that. I set the UI to disable, but I didn't actually changed the settings model (The `reset` button didn't show up in the top right hand corner)

You can just turn the volume to zero, as a work around for the time being.

Sorry about that! (Maybe I should also turn the default volume down lower as well)

**Comment by stirante** [comment]
Thanks, seems like lowering the volume did the trick. Also the rest of the settings were lost on update, but looks like they are saved properly.

**Comment by Unthrottled** [comment]
> all settings were lost 

That part is a bit concerning though. What settings didn't carry over? 

(I found another issue with the idle notification position, and the display (timed/focus) mode)

**Comment by stirante** [comment]
Settings I set and were lost:
 - Preferred gender
 - Preferred characters 
 - Allowed exit codes
 - Allow Waiting

Unfortunately I don't remember on which version I was before update.

**Comment by Unthrottled** [comment]
Thank you for the supporting information!

I will try to replicate the issue (losing other settings on update), so that I can try to find a fix.

I'd like to request more supporting information.

Please go to *IntelliJ IDEA -> About IntelliJ IDEA (Mac)* or *Help -> About IntelliJ IDEA (Windows)* and copy the infos
to the clipboard and paste it here.

It should contain:
* OS (Windows, Linux, Mac)
* IntelliJ Product + version (IDEA, RubyMine...)
* A list of enabled plugins

**Comment by stirante** [comment]
Sure, only deleted subscription info.
```
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: js.debugger.webconsole=false, go.run.processes.with.pty=false
Non-Bundled Plugins: CMD Support, GLSL, com.intellij.apacheConfig, com.jetbrains.plugins.ini4idea, com.intellij.plugins.watcher, com.mnr.java.intellij.idea.plugin.base64helper, de.netnexus.camelcaseplugin, io.unthrottled.amii, net.seesharpsoft.intellij.plugins.csv, org.antlr.intellij.plugin, org.jetbrains.plugins.go-template, org.jetbrains.plugins.localization, org.toml.lang, some.awesome, String Manipulation, VisualVMLauncher, com.euphoricity.gitignore, net.hexar.json2pojo, com.demonwav.minecraft-dev, com.stirante.commandlang, deno, org.jetbrains.plugins.vue, aws.toolkit, com.intellij.plugins.html.instantEditing, com.jetbrains.php, de.espend.idea.php.annotation, com.jetbrains.twig, izhangzhihao.rainbow.brackets, org.jetbrains.plugins.ruby, org.jetbrains.plugins.go, ru.adelf.idea.dotenv, org.rust.lang
```

**Comment by Unthrottled** [comment]
Wow! That's a lot of plugins..(I hope it isn't because of a conflict with one :sweat_smile:)
Thank you for the information, I'll look into the issue when I get the time.

If you feel extra motivated, and want to test something for me you could manually install the newest update for me.

Which can be done by:

Download the [latest release](https://github.com/Unthrottled/AMII/releases/latest) and install it manually using
  <kbd>Preferences</kbd> > <kbd>Plugins</kbd> > <kbd>⚙️</kbd> > <kbd>Install plugin from disk...</kbd>

If not, no big deal, I'll try to find the bug :crossed_fingers:

**Comment by stirante** [comment]
Manually updated and looks like settings are persisted now between updates. Also disabling sound works. As an extra bug, some character names are displayed very weirdly (probably because windows and it's weird encoding).
![image](https://user-images.githubusercontent.com/2420740/106003215-46035200-60b2-11eb-9683-26ba4a7696bc.png)

Still great plugin, I've never laughed that much when my code failed again and again.

**Comment by Unthrottled** [comment]
Great! 

I'll still try it on my end to make sure that it does the same thing. I'll look into the rendering on windows, worse case, I just remove the diacritics. Which can be fixed without you taking a new plugin update. 

I am also glad that you are in enjoying it as well!

**Comment by Unthrottled** [comment]
I just published the new update with this fix in it (should be available in the next coming days). 
I also changed the character names to not have any diacritics, so should be goo there for now.

I'll be more vigilant about settings changes in the future!
