### ISSUE TITLE
"Differentiate" opened projects in different window

### ISSUE THREAD

**Issue by InfRandomness** [Unthrottled/AMII#68]
Hi, I often work with two or more projects opened in the same IDE and I would like to know if it is possible to make it so that the plugin as independently per project,

right now whenever I click on my code when an AFK GIF appears, it clears both windows even if they don't have the same project opened.

(I may have failed to explain clearly, please let me know if you didn't understand).

**Comment by Unthrottled** [comment]
Just to make sure I am on the same page. 

Say for instance, you have intellij open with `project A` and `project B` open. When the AFK gif come up, when you return to `project B` you expect the AFK gif to stay on `project A`?

**Comment by Unthrottled** [comment]
Like this?

![Peek 2021-02-16 18-17](https://user-images.githubusercontent.com/15972415/108138287-4aa0a200-7083-11eb-9de2-513103407ab2.gif)

**Comment by InfRandomness** [comment]
Yeah, exactly

**Comment by Unthrottled** [comment]
@InfRandomness 
So I've got that change in, I don't plan on releasing it to the marketplace until #70 
In the mean time you can manually install the plugin if wanted, [see readme](https://github.com/Unthrottled/AMII#installation).

I didn't close this right away because I didn't know if you wanted each project to become AFK independently too. Right now, it triggers when you have been away from all projects. I'd have to look into if that is possible though.

**Comment by InfRandomness** [comment]
Hi, will build it myself and install it manually

I effectively wanted it to act independently on every single projects

**Comment by Unthrottled** [comment]
@InfRandomness I am planning on submitting the release latest release by the end of the day. Expect this to be available by Tuesday in the JetbBrains plugin repository.

Thank you for your interest and contribution!

**Comment by Unthrottled** [comment]
Turns out I didn't do a very good job, it still has some weird bugs.

**Comment by InfRandomness** [comment]
I will give this a try and try to see if bugs occur

**Comment by Unthrottled** [comment]
@InfRandomness 

Thanks for your assistance! Sorry about being so noisy.

There where 2 sneaky bugs that I fixed:

- Only Mouse press/clicks break count as activity now. Previously it was using mouse movement/hover/enter/exit events as well, which would reset the idle activity.
- Stacked projects no longer click through and dismiss notification behind them. This one is a bit hard to explain (and tricky to figure out it was happening). But if you had a project with an afk gif displayed, if you had another project (that you are working on)  on top of that project. When you click the area where the gif is on the project on the top, then it would dismiss the idle notification. I would be like, "Where is the gif? It was there before and I haven't been in the project" Turns out the mouse clicks where propagating through all project windows :sweat_smile: .
