### ISSUE TITLE
No reaction on successful exit codes: PyCharm

### ISSUE THREAD

**Issue by byamir** [Unthrottled/AMII#81]
Hello! Really love the extension, but I'm having a problem where it just ignores codes added in the settings as success codes. _"... MIKU will not react to these (but can if you want to)."_ How do I enable positive reactions on those exit codes?

**Comment by Unthrottled** [comment]
I made the negative exit code reaction blacklist exit codes that where not successful, because anything other than zero isn't success. That way it covers all of the bases for that feature.

I could add a separate part which enables MIKU to react to the positive exit codes. This wouldn't be enabled by default, but you could turn it on. You would provide a whitelisted set of exit codes for a positive reaction. I think I would make the positive reactions take priority. Such as if exit code `-1` is configured to be a positive reaction and is not present in the allowed exit codes, then you'll get a positive reaction.

**Comment by byamir** [comment]
That would be amazing. I tried to play around with it myself, but couldn't get it to work. I think that feature would be really useful!

**Comment by Unthrottled** [comment]
So I've got that change in, I don't plan on releasing it to the marketplace right away (Just released a new version).
 
In the mean time you can download and manually install the plugin  if wanted, [see the docs](https://github.com/Unthrottled/AMII#installation).

Thanks for the suggestion (I might need to add more positive reaction gifs now)

**Comment by byamir** [comment]
Appreciate the quick response! If it helps for future development, my personal use case is solving leetcode type questions using the [EPI book](https://github.com/adnanaziz/EPIJudge). Nothing would be more rewarding than a happy reaction when you finally get the answer right.
